---

- name: install mdns-daemon
  pkgng:
    name: dns/mdnsd
    state: present

- name: install nss_mdns
  pkgng:
    name: dns/nss_mdns
    state: present

- name: enable mdns resolution
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: "^hosts:"
    line: "hosts: files dns mdns"
  tags: [config]

- name: enable dbus
  service:
    name: dbus
    enabled: yes
  notify: start dbus

- name: flush handlers to ensure dbus is started before avahi-daemon
  meta: flush_handlers

- name: enable avahi-daemon
  service:
    name: avahi-daemon
    enabled: yes
    pattern: avahi-daemon
  notify: start avahi
