---

- name: install rutorrent dependencies
  pkgng: name={{ item }} state=present
  with_items: [ffmpeg, mediainfo, unrar]

- name: create rutorrent user
  user: name=rutorrent groups=media,rtorrent state=present
        home=/usr/local/www/rutorrent
        createhome=no

- name: add the www user to the rtorrent group
  user: name=www groups=rtorrent append=yes
  notify: restart nginx

- name: create rutorrent webdir
  file: path=/usr/local/www/rutorrent state=directory
        owner=root group=wheel mode=0755

- name: clone rutorrent
  git: repo=https://github.com/Novik/ruTorrent.git
       dest=/usr/local/www/rutorrent
       version=ac2db1536302bdc5b27aff6b15d54b0e9837fa59
       update=no
  register: rutorrent_cloned

- name: set base permissions on rutorrent files
  file: path=/usr/local/www/rutorrent state=directory
        recurse=yes
        owner=root group=wheel mode='u=rwX,go=rX'
  when: rutorrent_cloned|changed

- name: change owner of share/ to rutorrent
  file: path=/usr/local/www/rutorrent/share state=directory
        recurse=yes
        owner=rutorrent group=wheel mode='u=rwX,go=rX'

- name: copy labels to rutorrent tracklabels plugin
  copy: src=labels/ dest=/usr/local/www/rutorrent/plugins/tracklabels/labels
        owner=root group=wheel mode=644
  with_items: [couchpotato.png, sonarr.png]

- name: configure rutorrent
  template: src=config.php dest=/usr/local/www/rutorrent/conf/config.php
            owner=root group=wheel mode=644
  tags: [config]

- name: create php-fpm pool folder
  file: path=/usr/local/etc/fpm-pool.d state=directory
        owner=root group=wheel mode=0755

- name: enable php-fpm pool configs
  lineinfile:
    dest: /usr/local/etc/php-fpm.conf
    line: include=etc/fpm-pool.d/*.conf
  notify: restart php-fpm

- name: create rutorrent php pool
  template: src=php-pool.conf dest=/usr/local/etc/fpm-pool.d/rutorrent.conf
            owner=root group=wheel mode=644
  notify: restart php-fpm
  tags: [config]

- name: create the nginx vhost
  template: src=nginx-vhost.conf dest=/usr/local/etc/nginx/sites-available/rutorrent
            owner=root group=wheel mode=644
  notify: reload nginx
  tags: [config]

- name: enable the vhost
  file: src=/usr/local/etc/nginx/sites-available/rutorrent
        dest=/usr/local/etc/nginx/sites-enabled/rutorrent
        state=link
  notify: reload nginx
