---

- name: start dnscrypt-proxy
  service:
    name: dnscrypt-proxy
    state: started

- name: restart dnscrypt-proxy
  service:
    name: dnscrypt-proxy
    state: restarted

- name: start unbound
  service:
    name: local_unbound
    state: started

- name: restart unbound
  service:
    name: local_unbound
    state: restarted
