---

# Guide: https://wiki.mattrude.com/FreeNAS/Unifi_Controller_Install
# fstab and portsnap parts do not seem to be necessary

- name: install unifi dependencies
  pkgng: name={{ item }} state=present
  with_items: [openjdk8, texinfo]

- name: install mongodb
  pkgng: name=mongodb state=present

- name: install unifi
  command: make install
           chdir=/usr/ports/net-mgmt/unifi5/
           creates=/usr/local/etc/rc.d/unifi
  environment:
    BATCH: "yes"

- name: monitor unifi logs
  copy: src=unifi.filebeat.yaml dest=/usr/local/etc/filebeat.d/unifi.yml
        owner=root group=wheel mode=0644
  notify: restart filebeat
  tags: [logs]

- name: enable mongodb
  service: name=mongodb enabled=yes
  notify: start mongod

- name: enable unifi
  service: name=unifi enabled=yes
  notify: start unifi
