---

- name: start unifi
  service: name=unifi state=started enabled=yes

- name: restart unifi
  service: name=unifi state=restarted enabled=yes

- name: start mongodb
  service: name=mongod state=started enabled=yes

- name: restart mongodb
  service: name=mongod state=restarted enabled=yes
