---

- name: install sonarr
  pkgng: name=sonarr state=present
  notify: restart sonarr

- name: add the sonarr user to the media group
  user: name=sonarr groups=media append=yes
  notify: restart sonarr

- name: allow sonarr to auto-update
  file: path=/usr/local/share/sonarr state=directory
        recurse=yes
        owner=sonarr group=wheel mode='u=rwX,go=rX'

- name: enable sonarr
  service: name=sonarr enabled=yes
  notify: start sonarr
