---

- name: install grafana
  pkgng: name=grafana4 state=present
  notify: restart grafana

- name: install influxdb
  pkgng: name=influxdb state=present
  notify: restart influxdb

- name: install telegraf
  pkgng: name=telegraf state=present
  notify: restart telegraf

- name: install other dependencies
  pkgng: name={{ item }} state=present
  with_items:
    - collectd5
    - ipmitool

- name: configure grafana
  template: src=grafana.conf dest=/usr/local/etc/grafana.conf
            owner=root group=wheel mode=0644
  notify: restart grafana

- name: install grafana plugins
  command: grafana-cli plugins install {{ item }}
           creates=/var/db/grafana/plugins/{{ item }}
  with_items: "{{ grafana_plugins }}"

- name: configure influxdb
  template: src=influxd.conf dest=/usr/local/etc/influxd.conf
            owner=root group=wheel mode=0644
  notify: restart influxdb

- name: configure telegraf
  template: src=telegraf.conf dest=/usr/local/etc/telegraf.conf
            owner=root group=wheel mode=0644
  notify: restart telegraf

- name: enable influxdb
  service: name=influxd enabled=yes
  notify: start influxdb

- name: enable telegraf
  service: name=telegraf enabled=yes
  notify: start telegraf

- name: enable grafana
  service: name=grafana enabled=yes
  notify: start grafana

- name: flush handlers to start influxdb before creating database
  meta: flush_handlers

- name: create influxdb databases
  command: influx -execute 'CREATE DATABASE {{ item }}'
  with_items:
    - collectd
    - telegraf
