filebeat:
  prospectors:
    - paths: [/usr/local/share/java/unifi/logs/server.log]
      encoding: utf-8
      fields:
        program: unifi
      fields_under_root: true
      multiline:
        pattern: '^[^\[]'
        match: after
