---

- name: install sabnzbd
  pkgng:
    name: sabnzbdplus
    state: present

- name: add the sabnzbd user to the media group
  user: name=_sabnzbd groups=media append=yes
  notify: restart nginx

- name: add the www user to the sabnzbd group
  user: name=www groups=_sabnzbd append=yes
  notify: restart nginx

- name: create sabnzbd script dir in home
  file:
    path: /usr/local/sabnzbd/scripts
    state: directory
    owner: _sabnzbd
    group: media
    mode: 0755

- name: configure nzbtomedia
  include: nzbtomedia.yaml

- name: create the nginx vhost
  template:
    src: nginx-vhost.conf
    dest: /usr/local/etc/nginx/sites-available/sabnzbd
    owner: root
    group: wheel
    mode: 644
  notify: reload nginx
  tags: [config]

- name: enable the vhost
  file:
    src: /usr/local/etc/nginx/sites-available/sabnzbd
    dest: /usr/local/etc/nginx/sites-enabled/sabnzbd
    state: link
  notify: reload nginx

- name: enable sabnzbd
  service:
    name: sabnzbd
    enabled: yes
  notify: start sabnzbd
