---

- name: create alternative domain vhosts
  template: src=alt-domains-vhost.conf dest=/usr/local/etc/nginx/sites-available/{{ item.name }}
            owner=root group=wheel mode=644
  notify: reload nginx
  with_items: "{{ reverse_proxy_alt_domains }}"

- name: enable alternative domain vhosts
  file: src=/usr/local/etc/nginx/sites-available/{{ item.name }}
        dest=/usr/local/etc/nginx/sites-enabled/{{ item.name }}
        state=link
  notify: reload nginx
  with_items: "{{ reverse_proxy_alt_domains }}"

- name: configure alternative domain redirect locations on subdirs domain
  template: src=alt-domains-location.conf
            dest=/usr/local/etc/nginx/reverse-proxy/locations/{{ item.name }}
            owner=root group=wheel mode=0644
  notify: reload nginx
  with_items: "{{ reverse_proxy_alt_domains }}"
