---

# From: https://github.com/cloudflare/nginx-google-oauth

- name: create nginx lua module loading configuration
  template: src=lua-module.load dest=/usr/local/etc/nginx/mods-available/lua-module.load
            owner=root group=wheel mode=644
  notify: reload nginx

- name: enable nginx lua module
  file: src=/usr/local/etc/nginx/mods-available/lua-module.load
        dest=/usr/local/etc/nginx/mods-enabled/lua-module.load
        state=link
  notify: reload nginx

- name: download cjson
  get_url: url=https://github.com/mpx/lua-cjson/archive/2.1.0.tar.gz
           dest=/usr/local/libdata/ansible/downloads/lua-cjson-2.1.0.tar.gz
           sha256sum=8449f696d56edf27a318daa315d324757bf68120306fecbeb28a66b86077d8cd

- name: extract cjson
  command: tar -xvzf /usr/local/libdata/ansible/downloads/lua-cjson-2.1.0.tar.gz
           -C /usr/local/libdata/ansible/downloads/
           creates=/usr/local/libdata/ansible/downloads/lua-cjson-2.1.0

- name: install cjson
  command: make install LUA_INCLUDE_DIR=/usr/local/include/luajit-2.0/
           chdir=/usr/local/libdata/ansible/downloads/lua-cjson-2.1.0
           creates=/usr/local/lib/lua/5.1/cjson.so

- name: download resty.http
  get_url: url=https://github.com/pintsized/lua-resty-http/archive/v0.10.tar.gz
           dest=/usr/local/libdata/ansible/downloads/lua-resty.http-0.10.tar.gz
           sha256sum=6917ab4fd0dcd99df076e238f591aeaa9e2d7e0bca4904ebeb3c1bd418e7c1b9

- name: extract resty.http
  command: tar -xvzf /usr/local/libdata/ansible/downloads/lua-resty.http-0.10.tar.gz
           -C /usr/local/libdata/ansible/downloads/
           creates=/usr/local/libdata/ansible/downloads/lua-resty-http-0.10

# *.lua files are expected to be in /usr/local/share while *.so files are expected to be in /usr/local/lib
# The resty.http Makefile is a bit weird and installs its *.lua files to ../lib,
# so we fix that with LUA_LIB_DIR=...
- name: install resty.http
  command: make install LUA_INCLUDE_DIR=/usr/local/include/luajit-2.0/ LUA_LIB_DIR=/usr/local/share/luajit-2.0.5/
           chdir=/usr/local/libdata/ansible/downloads/lua-resty-http-0.10
           creates=/usr/local/lib/lua/5.1/resty

- name: install google-oauth lua module to nginx
  get_url: url=https://raw.githubusercontent.com/cloudflare/nginx-google-oauth/55799855193f419d70b26ad1b9c259664393bca4/access.lua
           dest=/usr/local/etc/nginx/reverse-proxy/google-oauth.lua
           sha256sum=23c8093a60771efa674683b2f2ac7676f80982770136d96df5cc0902abed2896
           owner=root group=wheel mode=644
  notify: reload nginx

- name: create google-oauth module configuration
  template: src=google-oauth.conf dest=/usr/local/etc/nginx/reverse-proxy/google-oauth.conf
            owner=root group=wheel mode=644
  notify: reload nginx
