---

- name: install acme-client
  pkgng:
    name: acme-client
    state: present

- name: remove the default acme challenge dir
  file:
    path: /usr/local/www/acme
    state: absent

- name: create .well-known dir
  file:
    path: public
    dest: /usr/local/www/public/{{ item }}
    state: directory
    owner: root
    group: wheel
    mode: 0755
  loop:
  - .well-known
  - .well-known/acme-challenge

- name: configure acme-client to run weekly
  template:
    src: letsencrypt.conf
    dest: /etc/periodic.conf
    owner: root
    group: wheel
    mode: 0755
  # config file changes might not impact the certificate
  # but there's no harm in running a request.
  # acme-client will know what's up.
  notify: request letsencrypt certificate
  tags: [config]

- name: request letsencrypt certificate for the first time
  command: >
    /usr/local/bin/acme-client -N -n -e
    -C /usr/local/www/public/.well-known/acme-challenge
    {{ reverse_proxy_domain }}
    {{ reverse_proxy_alt_domains|map(attribute='domain')|join(' ') }}
  args:
    creates: /usr/local/etc/ssl/acme/fullchain.pem
  notify: reload nginx
