---

- name: install acme-client
  pkgng: name=acme-client state=present

- name: remove the default acme challenge dir
  file: path=/usr/local/www/acme state=absent

- name: create .well-known dir
  file: path=public dest=/usr/local/www/public/{{ item }}
        state=directory
        owner=root group=wheel mode=755
  with_items:
    - .well-known
    - .well-known/acme-challenge

- name: configure acme-client to run weekly
  template: src=letsencrypt.conf dest=/etc/periodic.conf
            owner=root group=wheel mode=0755
  # config file changes might not impact the certificate
  # but there's no harm in running a request.
  # acme-client will know what's up.
  notify: request letsencrypt certificate
  tags: [config]
