---

- name: check if reverse_proxy_domain is defined
  fail: msg="reverse_proxy_domain is undefined. Set it in host_vars/reverse-proxy@freenas.local.yaml"
  when: reverse_proxy_domain is not defined

- name: configure public site
  include: public.yaml

- name: flush handlers to reload nginx config
  meta: flush_handlers

- name: configure letsencrypt
  include: letsencrypt.yaml

- name: configure htpasswd file
  copy:
    dest: /usr/local/etc/nginx/htpasswd
    content: "{{ reverse_proxy_htpasswd }}"
    owner: root
    group: www
    mode: 0440

- name: configure nginx proxy params
  template: src=proxy_params dest=/usr/local/etc/nginx/proxy_params
            owner=root group=wheel mode=0644
  notify: reload nginx

- name: configure subdirs
  include: subdirs.yaml

- name: configure altdomains
  include: alt-domains.yaml
