---

- name: copy public assets
  copy: src=public dest=/usr/local/www/
        owner=root group=wheel mode=644

- name: create public vhost
  template: src=public-vhost.conf dest=/usr/local/etc/nginx/sites-available/public
            owner=root group=wheel mode=644
  notify: reload nginx

- name: enable public vhost
  file: src=/usr/local/etc/nginx/sites-available/public
        dest=/usr/local/etc/nginx/sites-enabled/public
        state=link
  notify: reload nginx
