---

- name: create public dir
  file: path=/usr/local/www/public state=directory
        owner=root group=wheel mode=755

- name: create 50x.html
  copy: src=50x.html dest=/usr/local/www/public/50x.html
        owner=root group=wheel mode=644

- name: create public vhost
  template: src=public-vhost.conf dest=/usr/local/etc/nginx/sites-available/public
            owner=root group=wheel mode=644
  notify: reload nginx

- name: enable public vhost
  file: src=/usr/local/etc/nginx/sites-available/public
        dest=/usr/local/etc/nginx/sites-enabled/public
        state=link
  notify: reload nginx
