---

- name: install dnscrypt-proxy
  pkgng: name=dnscrypt-proxy state=present
  notify: restart dnscrypt-proxy

- name: configure dnscrypt-proxy resolver
  lineinfile:
    dest: /etc/rc.conf
    line: dnscrypt_proxy_resolver={{ dnscrypt_resolver_name }}
  notify: restart dnscrypt-proxy

- name: configure dnscrypt-proxy resolver
  lineinfile:
    dest: /etc/rc.conf
    line: dnscrypt_proxy_resolver="{{ dnscrypt_resolver_name }}"
  notify: restart dnscrypt-proxy

- name: configure dnscrypt-proxy listening interface
  lineinfile:
    dest: /etc/rc.conf
    line: dnscrypt_proxy_flags="-a 127.0.0.1:5300"
  notify: restart dnscrypt-proxy

- name: install unbound
  pkgng: name=unbound state=present
  notify: restart unbound

- name: configure unbound
  template: src=unbound.conf dest=/usr/local/etc/unbound/unbound.conf
            owner=root group=wheel mode=644
  notify: restart unbound

- name: enable dnscrypt-proxy
  service: name=dnscrypt-proxy enabled=yes
  notify: start dnscrypt-proxy

- name: enable unbound
  service: name=unbound enabled=yes
  notify: start unbound
