---

- name: install dnscrypt-proxy2
  pkgng:
    name: dnscrypt-proxy2
    state: present

- name: install unbound
  pkgng:
    name: unbound
    state: present
  notify: restart unbound

- name: configure dnscrypt-proxy resolver list
  lineinfile:
    dest: /usr/local/etc/dnscrypt-proxy/dnscrypt-proxy.toml
    line: server_names = {{ dnscrypt_resolvers | to_json }}
    regexp: ^server_names
  notify: restart dnscrypt-proxy
  tags: [config]

- name: configure dnscrypt-proxy listening port
  lineinfile:
    dest: /usr/local/etc/dnscrypt-proxy/dnscrypt-proxy.toml
    line: listen_addresses = ['127.0.0.1:5300']
    regexp: ^listen_addresses
  notify: restart dnscrypt-proxy
  tags: [config]

- name: configure unbound
  template:
    src: unbound.conf
    dest: /var/unbound/unbound.conf
    owner: root
    group: wheel
    mode: 0644
  notify: restart unbound
  tags: [config]

- name: enable dnscrypt-proxy
  service:
    name: dnscrypt-proxy
    enabled: yes
  notify: start dnscrypt-proxy

- name: enable unbound
  service:
    name: local_unbound
    enabled: yes
  notify: start unbound
