---

- name: download hello hue
  get_url: url=https://github.com/ledge74/HelloHue/archive/1.1.7.tar.gz
           dest=/usr/local/libdata/ansible/downloads/hello-hue-1.1.7.tar.gz
           sha256sum=1edf4868ee08ae1591b3facfba581cfb24ba46c2def90f2218f8f03da24d0558
  register: hello_hue_downloaded

- name: create hello hue bundle dir
  file: path="/usr/local/plexdata/Plex Media Server/Plug-ins/HelloHue.bundle"
        state=directory

- name: install hello hue
  command: tar -xvzf /usr/local/libdata/ansible/downloads/hello-hue-1.1.7.tar.gz
           -C "/usr/local/plexdata/Plex Media Server/Plug-ins/HelloHue.bundle"
           --strip-components 1
           HelloHue.bundle-1.1.7
           creates="/usr/local/plexdata/Plex Media Server/Plug-ins/HelloHue.bundle/README.md"
  when: hello_hue_downloaded|changed
  notify: restart plex

- name: change owner of the hello hue plugin code to plex
  file: path='/usr/local/plexdata/Plex Media Server/Plug-ins/HelloHue.bundle' state=directory
        recurse=yes
        owner=plex group=plex mode='u=rwX,go=rX'
