---

- name: download hello hue
  get_url: url=https://github.com/ledge74/HelloHue/archive/1.1.7.tar.gz
           dest=/usr/local/libdata/ansible/downloads/hello-hue-1.1.7.tar.gz
           sha256sum=042be3990fb042868c5053f8b89e2b2eac557c258f697d4cbfdd160f496300e5
  register: hello_hue_downloaded

- name: create hello hue bundle dir
  file: path=/usr/local/plexdata/Plex\ Media\ Server/Plug-ins/HelloHue.bundle
        state=directory

- name: install hello hue
  command: tar -xvzf /usr/local/libdata/ansible/downloads/hello-hue-1.1.7.tar.gz
           -C /usr/local/plexdata/Plex\ Media\ Server/Plug-ins/HelloHue.bundle
           --strip-components 1
           HelloHue-1.1.7
           creates=/usr/local/plexdata/Plex\ Media\ Server/Plug-ins/HelloHue.bundle/README.md
  when: hello_hue_downloaded|changed
  notify: restart plex
