---

- name: install plex
  pkgng:
    name: plexmediaserver
    state: present

- name: flush handlers to start plex (plexdata dir needed in other tasks)
  meta: flush_handlers

- name: install trakt tv plugin
  include: trakt_tv.yaml

- name: install hello hue plugin
  include: hello_hue.yaml

- name: install twitch mod plugin
  include: twitch_mod.yaml

- name: install youtube tv plugin
  include: youtube_tv.yaml

- name: install web tools plugin
  include: web_tools.yaml

- name: monitor plex logs
  copy: src=plex.filebeat.yaml dest=/usr/local/etc/filebeat.d/plex.yml
        owner=root group=wheel mode=0644
  notify: restart filebeat
  tags: [logs]

- name: enable plex
  service:
    name: plexmediaserver
    enabled: yes
  notify: start plex
