---

- name: install plex
  pkgng:
    name: plexmediaserver
    state: present

- name: flush handlers to start plex (plexdata dir needed in other tasks)
  meta: flush_handlers

- name: install trakt tv plugin
  include: trakt_tv.yaml

- name: install hello hue plugin
  include: hello_hue.yaml

- name: install twitch mod plugin
  include: twitch_mod.yaml

- name: enable plex
  service:
    name: plexmediaserver
    enabled: yes
  notify: start plex
