---

- name: install plex
  pkgng: name=plexmediaserver state=present
  notify: restart plex

- name: flush handlers to start plex (plexdata dir needed in other tasks)
  meta: flush_handlers

- name: install trakt scrobble plugin
  include: trakt_scrobbler.yaml

- name: install hello hue plugin
  include: hello_hue.yaml

- name: install youtube tv plugin
  include: youtube.yaml

- name: enable plex
  service: name=plexmediaserver enabled=yes
  notify: start plex
