---

- name: download web tools
  get_url: url=https://github.com/ukdtom/WebTools.bundle/archive/3.0.0.tar.gz
           dest=/usr/local/libdata/ansible/downloads/web-tools-3.0.0.tar.gz
           sha256sum=1239f487858a286fc9f8d9bfa170357e0664a799363bc89d13d3548253334c8f
  register: web_tools_downloaded

- name: create web tools bundle dir
  file: path="/usr/local/plexdata/Plex Media Server/Plug-ins/WebTools.bundle"
        state=directory

- name: install web tools
  command: tar -xvzf /usr/local/libdata/ansible/downloads/web-tools-3.0.0.tar.gz
           -C "/usr/local/plexdata/Plex Media Server/Plug-ins/WebTools.bundle"
           --strip-components 1
           WebTools.bundle-3.0.0
          #  creates="/usr/local/plexdata/Plex Media Server/Plug-ins/WebTools.bundle/README.md"
  when: web_tools_downloaded|changed
  notify: restart plex

- name: change owner of the web tools plugin code to plex
  file: path='/usr/local/plexdata/Plex Media Server/Plug-ins/WebTools.bundle' state=directory
        recurse=yes
        owner=plex group=plex mode='u=rwX,go=rX'
